name: Build and Publish .NET Framework Library

on:
  push:
    branches:
      - main
      
env:
  PJ_NAME: TestLib/TestLib.csproj
  
jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore TestLib.sln

      - name: Build the project
        run: msbuild TestLib.sln /p:Configuration=Release

      - name: Pack the library
        run: nuget pack TestLib/TestLib.csproj -Prop Configuration=Release

      - name: Publish to GitHub Packages
        run: nuget push "*.nupkg" -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" -ApiKey ${{ secrets.GITHUB_TOKEN }}
